version: '3'

services:
  mq:
    image: rabbitmq
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=qWxPJrZCLeHZraNTWjEKHdJJxJyho8
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MQ_DEFAULT_USER=rabbitmq
      - MQ_DEFAULT_PASS=rabbitmq
      - MQ_DEFAULT_VHOST=/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mq
    volumes:
      - ./media:/app/media
volumes:
  postgres-data:
  
