# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 14:19
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_filepath),
        ),
    ]
