# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 08:54
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170915_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='guid',
            new_name='id'
        ),
    ]
