# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170921_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_persistent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
