# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_is_persistent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('location', models.CharField(max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('last_login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_login', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
