# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_previous_logins_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousLogins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('lat_lon', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_login', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='previous_logins',
            name='user',
        ),
        migrations.DeleteModel(
            name='Previous_logins',
        ),
    ]
