# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_previouslogins_cookie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouslogins',
            name='cookie_id',
        ),
        migrations.AddField(
            model_name='previouslogins',
            name='device_id',
            field=models.CharField(db_index=True, editable=False, max_length=40, null=True),
        ),
    ]
