# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171024_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouslogins',
            name='lat_lon',
        ),
        migrations.AddField(
            model_name='previouslogins',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='previouslogins',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
