# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171031_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouslogins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_logins', to=settings.AUTH_USER_MODEL),
        ),
    ]
