# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171031_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleioPartnerSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_site_url', models.URLField(db_index=True)),
                ('partner_site_name', models.CharField(max_length=200)),
                ('partner_site_logo_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='previouslogins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_logins', to=settings.AUTH_USER_MODEL),
        ),
    ]
