# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171208_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PleioPartnerSites',
            new_name='PleioPartnerSite',
        ),
    ]
