# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171211_1518'),
        ('core', '0013_auto_20171120_1902'),
    ]

    operations = [
    ]
