# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20171213_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
