# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pleiohtmlsnippets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleioLegalTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(db_index=True, max_length=50)),
                ('language_code', models.CharField(max_length=10)),
                ('legal_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PleioHTMLSnippets',
        ),
    ]
