# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180220_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PleioLegalTexts',
            new_name='PleioLegalText',
        ),
    ]
