# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 08:14
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180220_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_filepath),
        ),
    ]
