# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-08 08:58
from __future__ import unicode_literals

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedAvatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_large_filename)),
                ('medium', models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_medium_filename)),
                ('small', models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_small_filename)),
                ('tiny', models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_tiny_filename)),
                ('topbar', models.ImageField(blank=True, null=True, upload_to=core.helpers.unique_avatar_topbar_filename)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='croppedavatars',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
