"""
Django settings for concierge project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#directory containing settings and Server Provider certificate for SAML
SAML_FOLDER = os.path.join(BASE_DIR, 'saml/configuration')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

FROM_EMAIL = 'noreply@pleio.nl'
SUPPORT_EMAIL = 'support@pleio.org'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25

TIME_ZONE = 'Europe/Amsterdam'

EXTERNAL_HOST = 'https://www.concierge.nl/'
EMAIL_LOGO = '/images/email-logo.png'

SITE_TITLE = 'Pleio'
SITE_LOGO = 'images/logo.svg'
SITE_FAVICON = 'images/favicon.png'

#This setting controls whether an image should be displayed when a user is also a member of other group(s) than "Any"
SHOW_GOVERNMENT_BADGE = True

# Send users a warning message when suspicious behaviour on their account occurs, e.g. a login on the account from a new (unknown) location.
SEND_SUSPICIOUS_BEHAVIOR_WARNINGS = True

#Google reCAPTCHA Will be present on login page when from that IP adress more than RECAPTCHA_NUMBER_INVALID_LOGINS during the last RECAPTCHA_MINUTES_THRESHOLD have occurred.
RECAPTCHA_MINUTES_THRESHOLD = 30
RECAPTCHA_NUMBER_INVALID_LOGINS = 10 

# Request an API key at https://developers.google.com/recaptcha/ for reCAPTCHA validation.

# With the following test keys, you will always get No CAPTCHA and all verification requests will pass.
GOOGLE_RECAPTCHA_SITE_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
GOOGLE_RECAPTCHA_SECRET_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

SAML2_SP = {
    "entityId": "http://172.17.0.1:8000/saml/metadata/",
    "assertionConsumerService": {
        "url": "http://172.17.0.1:8000/saml/acs/",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "singleLogoutService": {
        "url": "http://172.17.0.1:8000/saml/slo/",
        "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    "x509cert": "MIICUjCCAbugAwIBAgIBADANBgkqhkiG9w0BAQ0FADBGMQswCQYDVQQGEwJubDEQMA4GA1UECAwHVXRyZWNodDEOMAwGA1UECgwFUGxlaW8xFTATBgNVBAMMDHd3dy5wbGVpby5ubDAeFw0xODAxMzAxMzU0MzdaFw0xOTAxMzAxMzU0MzdaMEYxCzAJBgNVBAYTAm5sMRAwDgYDVQQIDAdVdHJlY2h0MQ4wDAYDVQQKDAVQbGVpbzEVMBMGA1UEAwwMd3d3LnBsZWlvLm5sMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCy2HWJ7r9rED7Femo32cgmcV1vSzkJarE5oS1HKkTwPRoXJK3TFU9CeF45GOOvpEcxcCZkz+e0JeU3+8lir+fhu2aZsNSqdPc56qrHsQk0/EkzPLIfUe0pVI0OSnAm82X43RWw0Jl/46U8ZUcpzuM2ltswkRBIr1o3eRyuyR83HwIDAQABo1AwTjAdBgNVHQ4EFgQUYOL49JvyZjjaomA4RnsVjKGAKOEwHwYDVR0jBBgwFoAUYOL49JvyZjjaomA4RnsVjKGAKOEwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQ0FAAOBgQAfn+7GQQ1Lq2ZhGMc219U1/kbOIZuaTwCw0IVluoxLy5kzqY2huV/gl8UUFr3Inp/VoX1eUmOK5WFtbHRj79AP6NX7A1B9OBcQDMFI2kJDhZQc1+5JFuwLPElrdZYyuSoB5Ey/CMbAkicZjxPWwutn34on3erPDYkmAvn74kl9og==",
    "privateKey": ""
}

# Setting CELERY_ALWAYS_EAGER to "True"  will make task being executed locally in the client, not by a worker.
# Always use "False" in production environment.
CELERY_ALWAYS_EAGER = True | False

BROKER_URL = "amqp://localhost"