# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalid', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.SlugField(unique=True)),
                ('displayname', models.CharField(max_length=100)),
                ('entityId', models.URLField(max_length=256)),
                ('ssoId', models.URLField(max_length=256)),
                ('sloId', models.URLField(max_length=256)),
                ('x509cert', models.CharField(max_length=8192)),
            ],
        ),
        migrations.AddField(
            model_name='externalids',
            name='identityproviderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saml.IdentityProvider'),
        ),
        migrations.AddField(
            model_name='externalids',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
