# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='x509cert',
            field=models.TextField(),
        ),
    ]
