# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0003_auto_20180220_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprovider',
            name='sloId',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
