# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0004_auto_20180220_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityprovider',
            name='x509cert',
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='x509cert1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='x509cert2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
