# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0005_auto_20180320_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identityprovider',
            old_name='x509cert1',
            new_name='signing_x509cert1',
        ),
        migrations.RenameField(
            model_name='identityprovider',
            old_name='x509cert2',
            new_name='signing_x509cert2',
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='encryption_x509cert1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='encryption_x509cert2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='perform_slo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='identityprovider',
            name='ssoId',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
