# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0008_identityprovider_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdpEmailDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('identityproviderid', models.ForeignKey(db_column='IdentityProvider.shortname', on_delete=django.db.models.deletion.CASCADE, to='saml.IdentityProvider')),
            ],
        ),
    ]
