# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0009_idpemaildomains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idpemaildomains',
            old_name='identityproviderid',
            new_name='identityprovider',
        ),
    ]
