# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0010_auto_20180327_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='metadata_filename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='metadata_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
