# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saml', '0012_auto_20180404_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalIds',
            new_name='ExternalId',
        ),
        migrations.RenameModel(
            old_name='IdpEmailDomains',
            new_name='IdpEmailDomain',
        ),
    ]
